### ISSUE TITLE
Failing to install after v1.0.1

### ISSUE THREAD

**Issue by Stuk** [crypto-browserify/EVP_BytesToKey#9]
Hi, this package is now failing to install:

```
$ npm install evp_bytestokey

> evp_bytestokey@1.0.1 install /private/tmp/test/node_modules/evp_bytestokey
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /private/tmp/test/node_modules/evp_bytestokey) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/knightle/.config/fnm/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/knightle/.config/fnm/bin/node" "/Users/knightle/.config/fnm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/test/node_modules/evp_bytestokey
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/knightle/.config/fnm/bin/node" "/Users/knightle/.config/fnm/bin/npm" "install" "evp_bytestokey"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! evp_bytestokey@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the evp_bytestokey@1.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the evp_bytestokey package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs evp_bytestokey
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls evp_bytestokey
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/test/npm-debug.log
```

Installing version 1.0.0 works:

```
$ npm install evp_bytestokey@1.0.0
/private/tmp/test
└─┬ evp_bytestokey@1.0.0
  └─┬ create-hash@1.1.3
    ├─┬ cipher-base@1.0.4
    │ └── safe-buffer@5.1.1
    ├── inherits@2.0.3
    ├─┬ ripemd160@2.0.1
    │ └── hash-base@2.0.2
    └── sha.js@2.4.8

npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
```

I am transitively using this package because `browserify-cipher` depends on it.

**Comment by moozzyk** [comment]
Seeing the same - it worked just fine in the morning.

**Comment by dcousens** [comment]
Investigating

**Comment by dcousens** [comment]
Published `v1.0.2` with `gypfile: false`... the gyp file was for testing only.

**Comment by Stuk** [comment]
Looks good here!

**Comment by dcousens** [comment]
Unpublished `v1.0.1`.

**Comment by brucewpaul** [comment]
👍 thanks

**Comment by moozzyk** [comment]
Builds are now passing. Thanks!

**Comment by mikaelm12** [comment]
Thanks for the lightening quick fix!

**Comment by elyscape** [comment]
@dcousens Please make sure to push the commit and tag for 1.0.2. Thanks!

**Comment by dcousens** [comment]
@elyscape thanks for reminder, done!

**Comment by jingleding** [comment]
@dcousens thank you very much！
